function Load(){
	ini_open("savedata.ini");
	global.highScore = ini_read_real("savegame", "highScore", 0);
	global.coins = ini_read_real("savegame", "coins", 0);
	global.fullscreen = ini_read_real("savegame", "fullscreen", 0);
	global.fastStart = ini_read_real("savegame", "fastStart", 0);
	global.music = ini_read_real("savegame", "music", 0);
	global.currentShopSelection = ini_read_real("savegame", "currentShopSelection", 0);
	global.playerSelection = ini_read_real("savegame", "playerSelection", 0);
	global.points50 = ini_read_real("savegame", "points50", 0);
	global.points100 = ini_read_real("savegame", "points100", 0);
	global.points200 = ini_read_real("savegame", "points200", 0);
	global.points300 = ini_read_real("savegame", "points300", 0);
	global.shop5 = ini_read_real("savegame", "shop5", 0);
	global.mysteryAchievement = ini_read_real("savegame", "mysteryAchievement", 0);
	global.shopOwnership[0] = ini_read_real("savegame", "shopOwnership0", 0);
	global.shopOwnership[1] = ini_read_real("savegame", "shopOwnership1", 0);
	global.shopOwnership[2] = ini_read_real("savegame", "shopOwnership2", 0);
	global.shopOwnership[3] = ini_read_real("savegame", "shopOwnership3", 0);
	global.shopOwnership[4] = ini_read_real("savegame", "shopOwnership4", 0);
	global.shopOwnership[5] = ini_read_real("savegame", "shopOwnership5", 0);
	global.shopOwnership[6] = ini_read_real("savegame", "shopOwnership6", 0);
	global.shopOwnership[7] = ini_read_real("savegame", "shopOwnership7", 0);
	global.shopOwnership[8] = ini_read_real("savegame", "shopOwnership8", 0);
	global.shopOwnership[9] = ini_read_real("savegame", "shopOwnership9", 0);
	global.shopOwnership[10] = ini_read_real("savegame", "shopOwnership10", 0);
	global.shopOwnership[11] = ini_read_real("savegame", "shopOwnership11", 0);
	global.shopOwnership[12] = ini_read_real("savegame", "shopOwnership12", 0);
	global.shopOwnership[13] = ini_read_real("savegame", "shopOwnership13", 0);
	global.shopOwnership[14] = ini_read_real("savegame", "shopOwnership14", 0);
	global.shopOwnership[15] = ini_read_real("savegame", "shopOwnership15", 0);
	global.shopOwnership[16] = ini_read_real("savegame", "shopOwnership16", 0);
	global.shopOwnership[17] = ini_read_real("savegame", "shopOwnership17", 0);
	ini_close();
}
